### ISSUE TITLE
Unable to load morphologies downloaded BBP EPFL project.

### ISSUE THREAD

**Issue by silentsilence1** [BlueBrain/TMD#28]
I was trying to use cell morphologies from https://bbp.epfl.ch/nmc-portal/downloads but these morphologies are provided in .asc and arent accepted by TMD. After converting it using NLMorphologyConverter I am yet unable to read the output .swc file. Is there a reader (like NeuroM) for .asc files in TMD?

**Comment by lidakanari** [comment]
I would propose to use for conversion the following tool:
https://github.com/BlueBrain/MorphIO
Just iterate over the morphologies you wish to convert and run the following:
```
cell = morphio.mut.Morphology("cell_file.asc")
cell.write("cell_file.swc")
```

**Comment by wizmer** [comment]
IMO, the proper way would be to merge https://github.com/BlueBrain/TMD/pull/18

**Comment by silentsilence1** [comment]
Thank you, that conversion tool worked extremely well.
