### ISSUE TITLE
ERROR: Package 'tmd' requires a different Python: 2.7.12 not in '>=3.6'

### ISSUE THREAD

**Issue by Adlily** [BlueBrain/TMD#31]

**Comment by ANHUIDANGSHAN** [comment]
Hello, I am very interested in your research. When I tried to implement your code and installed TMD Package according to the installation instructions, the problem "ERROR: Package 'TMD' requires a different Python: 2.7.12 not in '>=3.6' " occurs and then how to solve this problem.
My running environment is Windows10 +VMware+ubuntu16 +python2.7.17, 
Looking forward to your reply!

**Comment by wizmer** [comment]
Hi,
You need to use a more recent version of python. Ubuntu 16 ships with python3, that's what you should use.

**Comment by ANHUIDANGSHAN** [comment]
Thanks for your guidance! It works! Thanks!
