### ISSUE TITLE
When using TMD is the module case sensitive to swc, asc and h5 file types?

### ISSUE THREAD

**Issue by riddick-the-furyan** [BlueBrain/TMD#77]
I downloaded a dataset from ebrains because the previous dataset I used had incomplete data. When running my personal tutorial for neurots I ran into an AssertionError. 

The source code:

```
import json
from pathlib import Path

import neurots
from neurots import extract_input


def run(distr_dir, params_dir, neuron_dir, data_dir):
    for i in range(0,50,1):
        """Run the example for extracting inputs for synthesis."""
        # Generate distribution from directory of neurons

        distr_name = "test_distr_{}.json".format(i)
        params_name = "test_params_{}.json".format(i)
        neuron_name = "test_neuron_{}.swc".format(i)

        distr = extract_input.distributions(
            data_dir / "neurons",
            feature="path_distances", 
            diameter_model="default",
        )

        

if __name__ == "__main__":
    data_dir = Path("C:\\Users\\user\\Documents\\Experiment_01\\Data\\Human\\Neocortex_interneurons")
    params_dir = Path("C:\\Users\\user\\Documents\\Experiment_01\\Parameters\\Neocortex_interneuron")
    distr_dir = Path("C:\\Users\\user\\Documents\\Experiment_01\\Distributions\\Neocortex_interneuron")
    neuron_dir = Path("C:\\Users\\user\\Documents\\Experiment_01\\Synthesized\\Neurons\\Neocortex_interneuron")
    
    #result_dir.mkdir(parents=True, exist_ok=True)

    run(distr_dir, params_dir, neuron_dir, data_dir)
    print("DONE!!!")
```

The warning: "C:\Users\user\Documents\Experiment_01\Data\Human\Neocortex_interneurons\neurons\hbp-00938_morph-ChIN-STR_sbj1-160504_cell3_original__CIN_160504_slice2_Cell3ChaTcre_TdTomato_jofn_20170109.ASC is not a valid h5, swc or asc file. If asc set use_morphio to True.

I removed the files from their respective subfolders and all of the morphologies in a single folder. The folder contains both swc files and asc files but all of the swc files are in lowercase.

Dataset:
[interneurons_swc.zip](https://github.com/BlueBrain/TMD/files/11469543/interneurons_swc.zip)

Edit: Error occurs in line 214 in io.py after the extension was assert in line 207.

**Comment by adrien-berchet** [comment]
Hi @riddick-the-furyan 
Indeed the current version can not load files with upper-case extensions, I'm fixing this.
